package by.asonau.web_project.controller.concrete;

public enum CommandName {
	DO_AUTH,
	DO_REGISTRATION,
	DO_ADD_NEWS,
	DO_DELETE_NEWS,
	DO_EDIT_NEWS,
	DO_EDIT_ACCOUNT_PAGE,
	
	GO_TO_INDEX_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_AUTHENTICATION_PAGE,
	GO_TO_NEWS_PAGE,
	GO_TO_NEWS_BY_CATEGORY_PAGE,
	GO_TO_ACCOUNT_PAGE,
	GO_TO_ADD_NEWS_PAGE,
	GO_TO_MY_NEWS_PAGE,
	GO_TO_EDIT_NEWS_PAGE,
	GO_TO_EDIT_ACCOUNT_PAGE,

	NO_SUCH_COMMAND,
	LOGOUT,
	GENERATE_ERROR
}
